import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "@/lib/supabase/get-user";
import { UserStoreInitializer } from "@/providers/user-store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Servitec Time",
  description: "Generated by create next app",
  icons: "/favicon.svg",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const user = await getCurrentUser();

  return (
    <html
      lang="es"
      className={`light ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <UserStoreInitializer user={user} />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
